### ISSUE TITLE
Image cropper no longer working after recent UI changes

### ISSUE THREAD

**Issue by GoldstarZV** [7dJx1qP/stash-userscripts#11]
I believe this change has broken the image cropper:
https://github.com/stashapp/stash/commit/b8e2f2a0fa8cfa7969107b3b56c668cbc9f4fffe 

the button no longer shows under the performer image in the new UI

**Comment by MyDirtyAccount** [comment]
I believe I've fixed this (for tags - performers TBD) in #14

**Comment by 7dJx1qP** [comment]
I believe the userscripts have been mostly updated to support 0.24.3 but I will be updating only the plugin versions from now on https://github.com/7dJx1qP/stash-plugins
