### ISSUE TITLE
Major UI change in v22

### ISSUE THREAD

**Issue by thedesi1** [7dJx1qP/stash-userscripts#13]
A lot of scripts not working on performer and studio page because of major UI changes like copy stashID etc.

**Comment by ouenascender** [comment]
replaced studio-details with detail-container in file to resolve studio stash id updates

**Comment by 7dJx1qP** [comment]
I believe the userscripts have been mostly updated to support 0.24.3 but I will be updating only the plugin versions from now on https://github.com/7dJx1qP/stash-plugins
