### ISSUE TITLE
pip install pystashlib for a docker based stash install

### ISSUE THREAD

**Issue by letraitplat** [7dJx1qP/stash-userscripts#7]
Hello
thanks for your user scripts library. I'm eager to test it.
I realized after installing the plugins that I am now getting this error in logs : 

_[Plugin / Userscript Functions] If you have pip (normally installed with python), run this command in a terminal (cmd): pip install pystashlib)_

My bad, it was mentionned in the setup walkthrough to run this command. Issue is, I have no clue how to run it because I'm running stash on a docker based instance, on a qnap NAS.

When going in portainer to check the container, I realized there was a place to run commands but I'm getting issues : 

_/ $ pip install pystashlib
WARNING: The directory '/.cache/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you should use sudo's -H flag._

then

_Successfully built pyyaml
Installing collected packages: pyyaml, python-dateutil, pystashlib
ERROR: Could not install packages due to an OSError: [Errno 13] Permission denied: '/.local'
Check the permissions._

A bit of a Linux newbie here so bear with me if the question is ... well, newbie :)

Thanks

**Comment by letraitplat** [comment]
managed solving the issue, this can be closed
thanks

**Comment by i-am-at0m** [comment]
This doesn't solve the issue, because if you ever update the container it'll get blown away and you'll have to do it again.
